<?php
/**
 * Copyright © 2020 MageBig, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="block-brands-search" data-mage-init='<?= $block->getJsonConfig() ?>'>
    <div class="brand-search-index" >
        <div class="brand-search-form" data-role="brand-search-form">
            <input data-role="brand_search_input" placeholder="<?= __('Search brand here') ?>" type="text" class="input-text brand-search-input" />
            <i class="mbi mbi-magnifier"></i>
            <div data-role="brand-list-wrap" class="brand-list-wrap"></div>
        </div>
    </div>
</div>
