<?php
/**
 * Copyright © 2020 MageBig, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="block block-brand-search filter" data-mage-init='<?= $block->getJsonConfig() ?>'>
	<div class="block-title"><strong class="title"><?php echo __('Search Brand') ?></strong></div>
    <div class="block-content">
        <div class="brand-search-wrap" >
            <div class="brand-search-form" data-role="brand-search-form">
                <input data-role="brand_search_input" type="text" class="input-text brand-search-input" />
                <i class="mbi mbi-magnifier"></i>
                <div data-role="brand-list-wrap" class="brand-list-wrap"></div>
            </div>
        </div>
    </div>
</div>
