<?php
$i = 0;
?>
<?php if (!$carousel) : ?>
<div class="product-items row">
    <?php endif ?>
    <?php foreach ($collection as $_product): ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel owl-theme">
        <?php endif ?>
        <?php if (($i % $column == 0 || ($row > 1 && $i % $row == 0)) && $carousel): ?>
        <div class="category-products">
        <div class="product-items <?= $type; ?> <?= $carousel && $row == 1 ? ' owl-carousel owl-theme' : '' ?> <?= !$carousel ? ' row': '' ?>">
    <?php endif ?>

        <?php $i++ ?>
        <div class="product-item<?= !$carousel ? ' col-6 col-sm-4 col-md-3' : '' ?>">
            <div class="product-item-info">
                <div class="product-show">
                    <?php $productImage = $block->getImage($_product, $image); ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo">
                        <span class="main-photo">
                            <?= $productImage->toHtml(); ?>
                        </span>
                        <?php if ($isHover) : ?>
                            <?php $hoverImg = $block->getImage($_product, 'product_grid_hover'); ?>
                            <?php if (!strpos($hoverImg->getImageUrl(), 'mb_hover_img')) : ?>
                                <span class="hover-photo">
                                    <?= $hoverImg->toHtml(); ?>
                                </span>
                            <?php endif ?>
                        <?php endif ?>
                        <?php if ($labelHelper->getDiscountPercent($_product)) : ?>
                            <span class="discount-percent"><?= $labelHelper->getDiscountPercent($_product); ?></span>
                        <?php endif;?>
                    </a>
                </div>
            </div>
        </div>
        <?php if (($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)) && $carousel): ?>
        </div>
        </div>
    <?php endif ?>
        <?php if ($carousel && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
    <?php if (!$carousel) : ?>
</div>
<?php endif ?>
