<?php
/**
 * Copyright © www.magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php
$_filters = $block->getActiveFilters();
$count = count($_filters);
$helper = $this->helper('MageBig\Shopbybrand\Helper\Data');
$brandCode = $helper->getStoreBrandCode();
?>
<?php if (!empty($_filters) && $count > 1): ?>
<div class="filter-current">
    <strong class="block-subtitle filter-current-subtitle"
            role="heading"
            aria-level="2"
            data-count="<?= count($_filters) ?>"><?= /* @escapeNotVerified */ __('Now Shopping by') ?>: </strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): ?>
        <?php if($_filter->getFilter()->getRequestVar() != $brandCode) : ?>
            <?php
            $label = $_filter->getLabel();
            if (is_array($label)) {
                $label = implode(', ', $label);
            }
            ?>
            <li class="item">
                <span class="filter-label"><?= $block->escapeHtml(__($_filter->getName())) ?></span>
                <span class="filter-value"><?= $block->escapeHtml($block->stripTags($label)) ?></span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtmlAttr(__($_filter->getName()) . " " . $block->stripTags($label));
                if ($clearLinkUrl) :
                    ?>
                    <a class="action previous" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Previous')) ?>">
                        <span><?= $block->escapeHtml(__('Previous')) ?></span>
                    </a>
                    <a class="action remove"
                       title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?= $block->escapeUrl($clearLinkUrl) ?>">
                        <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                    </a>
                <?php else : ?>
                    <a class="action remove" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName ?>">
                        <span><?= $block->escapeHtml(__('x')) ?></span>
                    </a>
                <?php endif; ?>
            </li>
        <?php endif; ?>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
