<?php
/**
 * Copyright © www.magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block">
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= $filtered ?>">
            <strong data-role="title"><?= __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($filtered > 2): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php
                $helper = $this->helper('MageBig\Shopbybrand\Helper\Data');
                $brandCode = $helper->getStoreBrandCode();
                $helper = $this->helper('MageBig\AjaxFilter\Helper\Data');
                $expand = (int) $helper->getConfig('magebig_ajaxfilter/general/expand_box_state');
                if ($expand) {
                    $count = count($block->getFilters());
                    if ($expand > $count) {
                        $expand = $count;
                    }
                    $active = [];
                    for ($i = 0; $i < $expand; $i++) {
                        $active[] = $i;
                    }
                    $active = json_encode($active);
                } else {
                    $active = 'false';
                }
            ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                <?php if($filter->getRequestVar() != $brandCode) : ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= __('Shopping Options') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "opened",
                                "collapsible": true,
                                "active": <?= $active ?>,
                                "multipleCollapsible": true,
                                "animate": {"duration": 300}
                            }
                        }'>
                    <?php  $wrapOptions = true; endif; ?>
                    <div data-role="collapsible" class="filter-options-item <?= $filter->getRequestVar() ?>">
                        <div data-role="title" class="filter-options-title"><?= __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content">
                            <div class="filter-options-wrap">
                                <?= $block->getChildBlock('renderer')->render($filter) ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
