<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<span class="product-image-container"
      style="width:<?= $block->escapeHtmlAttr($block->getWidth()) ?>px;">
    <span class="product-image-wrapper img-lazy-wrap"
          style="padding-bottom: <?= ($block->getRatio() * 100) ?>%;">
        <img class="<?= $block->escapeHtmlAttr($block->getClass()) ?> media-lazy lazyload"
            <?php if (is_array($block->getCustomAttributes())) : ?>
                <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                    <?= $block->escapeHtmlAttr($name) ?>="<?= $block->escapeHtmlAttr($value) ?>"
                <?php endforeach; ?>
            <?php else : ?>
                <?= $block->getCustomAttributes() ?>
            <?php endif; ?>
            src="#"
            data-src="<?= $block->escapeUrl($block->getImageUrl()) ?>"
            width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
            height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
            alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
