<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_StorePickupWithLocator
 */
?>
<?php /** @var $block \Amasty\StorePickupWithLocator\Block\Adminhtml\Sales\Order\DateTime */ ?>
<div class="ampickup-date-info">
    <span class="ampickup-title"><?= $block->escapeHtml($block->getTitle()) ?></span>
    <span class="ampickup-date"><?= $block->escapeHtml($block->getDate()) ?></span>
    <span class="ampickup-time"><?= $block->escapeHtml($block->getTime()) ?></span>
</div>
