<?php
/** @var \Magento\Sales\Block\Order\Email\Items\DefaultItems $block */
$_item = $block->getItem();

/** @var \Magetrend\Email\Helper\Data $moduleHelper */
$moduleHelper = $block->getModuleHelper();
?>
<?php if ($moduleHelper->getSubtotalDisplayType($_item->getStoreId()) == \Magento\Tax\Model\Config::DISPLAY_TYPE_EXCLUDING_TAX) : ?>
<?php /* @escapeNotVerified */ echo $block->formatPrice($_item->getRowTotal());?>
<?php endif; ?>
<?php if ($moduleHelper->getSubtotalDisplayType($_item->getStoreId()) == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX) : ?>
    <?php /* @escapeNotVerified */ echo $block->formatPrice($_item->getRowTotalInclTax());?>
<?php endif; ?>
<?php if ($moduleHelper->getSubtotalDisplayType($_item->getStoreId()) == \Magento\Tax\Model\Config::DISPLAY_TYPE_BOTH) : ?>
    <?php /* @escapeNotVerified */ echo $block->formatPrice($_item->getRowTotalInclTax()) ;?>
<?php endif; ?>

