<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_StorePickupWithLocator
 */
?>
<button class="amlocator-button -pickup"
         data-ampickup-location="idForLocation"
         data-ampickup-js="choose-store"
         title="<?= $block->escapeHtml(__('Pick up here')) ?>">
    <?= $block->escapeHtml(__('Pick up here')) ?>
</button>
