<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_StorePickupWithLocator
 */
?>
<?php
/**
 * @var \Amasty\StorePickupWithLocator\Block\Location $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$locations = $block->getLocationCollection();
?>
<div class="amlocator-wrapper">
    <div class="amlocator-stores-wrapper">
        <?php foreach ($locations as $location): ?>
            <div class="amlocator-store-desc" name="leftLocation"
                 data-mapid="<?= $block->escapeHtml($block->getMapId()); ?>"
                 data-amid="<?= (int)$location['id']; ?>">
                <div class="amlocator-block">
                    <?php if ($baseImage = $block->getLocationImage($location)): ?>
                        <div class="amlocator-image"
                             style="background-image:
                                     url('<?= $block->escapeUrl($baseImage) ?>')">
                        </div>
                    <?php endif; ?>
                    <div class="amlocator-store-information">
                        <?= /* @noEscape */
                        $location->getStoreListHtml() ?>
                        <?php if (!$block->getDisablePickupButton()): ?>
                            <button class="amlocator-button -pickup"
                                    data-ampickup-location="<?= (int)$location->getId() ?>"
                                    data-ampickup-js="choose-store"
                                    title="<?= $block->escapeHtml(__('Pick up here')); ?>">
                                <?= $block->escapeHtml(__('Pick up here')); ?>
                            </button>
                        <?php endif; ?>
                    </div>
                </div>
                <?=
                $block->getLayout()
                    ->createBlock(\Amasty\Storelocator\Block\View\Schedule::class)
                    ->setData('location', $location)
                    ->toHtml();
                ?>
            </div>
        <?php endforeach; ?>
    </div>

    <?php if ($block->isExistBlockPager() && $pager = $block->getPagerHtml()): ?>
        <div class="amlocator-pager-container"><?= /** @escapeNotVerified */
            $pager; ?></div>
    <?php endif; ?>
</div>
