<?php $breadcrumbs = $block->getBreadcrumbs(); ?>
<?php if ($breadcrumbs && is_array($breadcrumbs)) : ?>
    <div class="wrapper-breadcrums">
        <div class="breadcrumbs container">
            <ul class="items">
                <?php foreach ($breadcrumbs as $crumbName => $crumbInfo) : ?>
                    <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                        <?php if ($crumbInfo['link']) : ?>
                            <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                        <?php else: ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
