<?php
$loaderIcon = $escaper->escapeUrl($block->getViewFileUrl('images/loader-2.gif'));
?>

<div class="mwdeliverymsg-loader-container -hidden"
     data-bind="scope: 'midoriweb.delivery-message'"
     data-mage-init='{"loader": { "icon": "<?= /* @noEscape */ $loaderIcon ?>"}}'>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
        }
    }
</script>
