<?php
/**
 * Copyright © 2018 Magenest. All rights reserved.
 */
// @codingStandardsIgnoreFile
$jsonData = $block->getStripeApplePayConfig();
$isInCatalog = $block->getIsInCatalogProduct();
$isCart = $block->getIsCart();
?>
<div class="payment-method"
     data-mage-init='{"Magenest_StripePayment/js/payment/stripe_button":{
        "is_catalog": "<?=boolval($isInCatalog)?>",
        "is_cart": "<?=boolval($isCart)?>",
        "json_data": <?=json_encode($jsonData)?>
     }}'>
</div>


