<div class="selling-feature-wrap">
  <div class="selling-feature">
    <div class="row align-items-center">
      <div class="col-6 col-lg-3">
        <div class="media list-features">
          <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-rocket">&nbsp;</i></div>
          <div class="media-body">
            <div class="media-heading h4">Free Delivery</div>
            <div class="text desc std">For all orders&nbsp;over&nbsp;€50</div>
          </div>
        </div>
      </div>
      <div class="col-6 col-lg-3">
        <div class="media list-features">
          <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-sync2">&nbsp;</i></div>
          <div class="media-body">
            <div class="media-heading h4">Hassle Free Returns</div>
            <div class="text desc std">Simple, Hassle Free Rerurns</div>
          </div>
        </div>
      </div>
      <div class="col-6 col-lg-3">
        <div class="media list-features">
          <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-store">&nbsp;</i></div>
          <div class="media-body">
            <div class="media-heading h4">Click &amp; Collect</div>
            <div class="text desc std">Order online &amp; Collect in Store</div>
          </div>
        </div>
      </div>
      <div class="col-6 col-lg-3">
        <div class="media list-features">
          <div class="media-left align-self-center mr-1 mr-sm-4"><i class="mbi mbi-paper-plane">&nbsp;</i></div>
          <div class="media-body">
            <div class="media-heading h4">Next Day Delivery</div>
            <div class="text desc std">Fast Delivery on over 17,000 products</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

