<script>
    require(['jquery','domReady!'],function($){
        var newVal,
            defaultValue = parseFloat($('#qty').val()),
            inrement = <?= $block->getProductQtyIncrements() ? $block->getProductQtyIncrements() : 1 ?>;

        $(".btn-qty").click(function (event) {
            var $button = $(this),
                $input = $button.closest('.control').find("input#qty"),
                oldValue = parseFloat($input.val());

            if (!oldValue || oldValue < inrement) {
                oldValue = 0;
            }

            if ($button.hasClass('plus')) {
                newVal = oldValue + inrement;
            } else {
                if (oldValue > defaultValue && oldValue - inrement > 0) {
                    newVal = oldValue - inrement;
                } else {
                    newVal = defaultValue;
                }
            }
            newVal = parseFloat(newVal.toFixed(10));
            $input.val(newVal);
        });
    });
</script>
