<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_StorePickupWithLocatorMSI
 */
?>
<?php
/**
 * @var $viewModel \Amasty\StorePickupWithLocatorMSI\ViewModel\Catalog\Product\Locations
 * @var $escaper Magento\Framework\Escaper
 */
$viewModel = $block->getViewModel();
$showMsiLocations = $viewModel->isShowLocationsWithMsi($block->getProductId());
$loaderIcon = $escaper->escapeUrl($block->getViewFileUrl('images/loader-2.gif'));
?>

<?php if ($showMsiLocations): ?>
    <div class="ampickupmsi-loader-container -hidden"
         data-bind="scope: 'ampickupmsi.locations'"
         data-mage-init='{"loader": { "icon": "<?= /* @noEscape */ $loaderIcon ?>"}}'
         data-ampickupmsi-js="locations-container">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <div data-bind="scope: 'ampickupmsi.locations.map'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
<?php endif; ?>

<div class="ampickupmsi-link-wrapper
     <?= $showMsiLocations === true ? ' -hidden' : ''?>"
     data-ampickupmsi-js="link-wrapper">
    <?= $block->getChildHtml('amlocator_link') ?>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout();?>
        }
    }
</script>
