<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_StorePickupWithLocator
 */
?>
<?php
/**
 * @var \Magento\Catalog\Block\Product\View $block
 * @var Magento\Framework\Escaper $escaper
 * @var \Amasty\StorePickupWithLocator\ViewModel\Catalog\Product\Banner $viewModel
 */

$viewModel = $block->getViewModel();
?>

<?php if ($viewModel && $viewModel->shouldDisplayBanner($block->getProduct())): ?>
    <div class="amlocator-curbside-banner-wrapper">
        <?= $viewModel->getBannerBlockHtml($block->getLayout()) ?>
    </div>
<?php endif; ?>